// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/contact.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/projects.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/ImageSlider.tsx";
import * as $$2 from "./islands/SocialsButton.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/contact.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/projects.tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/ImageSlider.tsx": $$1,
    "./islands/SocialsButton.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
